### ISSUE TITLE
node-red crashed with KafkaJSSASLAuthenticationError

### ISSUE THREAD

**Issue by cobolbaby** [emrebekar/node-red-contrib-kafkajs#12]
```
Welcome to Node-RED
===================

13 Sep 03:44:26 - [info] Node-RED version: v3.1.0
13 Sep 03:44:26 - [info] Node.js  version: v16.20.2
13 Sep 03:44:26 - [info] Linux 5.4.0-155-generic x64 LE
13 Sep 03:44:26 - [info] Loading palette nodes
13 Sep 03:44:28 - [info] Settings file  : /data/settings.js
13 Sep 03:44:28 - [info] Context store  : 'default' [module=memory]
13 Sep 03:44:28 - [info] User directory : /data
13 Sep 03:44:28 - [warn] Projects disabled : editorTheme.projects.enabled=false
13 Sep 03:44:28 - [info] Flows file     : /data/flows.json
13 Sep 03:44:28 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

13 Sep 03:44:28 - [info] Server now running at http://127.0.0.1:1880/
13 Sep 03:44:28 - [info] Starting flows
13 Sep 03:44:28 - [info] Started flows
{"level":"ERROR","timestamp":"2023-09-13T03:44:28.525Z","logger":"kafkajs","message":"[BrokerPool] SASL Plain: Invalid username or password","retryCount":0,"retryTime":295}
13 Sep 03:44:28 - [red] Uncaught Exception:
13 Sep 03:44:28 - [error] KafkaJSSASLAuthenticationError: SASL Plain: Invalid username or password
    at PlainAuthenticator.authenticate (/usr/src/node-red/node_modules/kafkajs/src/broker/saslAuthenticator/plain.js:14:13)
    at SASLAuthenticator.authenticate (/usr/src/node-red/node_modules/kafkajs/src/broker/saslAuthenticator/index.js:73:77)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/src/node-red/node_modules/kafkajs/src/broker/index.js:100:9
    at async Broker.connect (/usr/src/node-red/node_modules/kafkajs/src/broker/index.js:158:7)
    at async /usr/src/node-red/node_modules/kafkajs/src/cluster/brokerPool.js:95:9
    at async Cluster.connect (/usr/src/node-red/node_modules/kafkajs/src/cluster/index.js:109:5)
    at async Object.connect (/usr/src/node-red/node_modules/kafkajs/src/producer/index.js:219:7)
    at async KafkajsProducerNode.init (/usr/src/node-red/node_modules/node-red-contrib-kafkajs/js/kafka-producer.js:65:13)
```

**Comment by emrebekar** [comment]
Thanks for the improvement. I have merged the changes.
