### ISSUE TITLE
Kafka producer crashes Node-red at startup if cannot connect to broker

### ISSUE THREAD

**Issue by omrid01** [emrebekar/node-red-contrib-kafkajs#6]
First I want to thank you for providing this excellent, full-featured node.
Apologies if this issue has already been raised and addressed.

When starting Node-red without an accessible Kafka broker to connect to, the "producer" node retries to connect 5 times and then throws an unhandled exception which crashes the whole NR server process. I need to keep the node disabled, and enable it only when Kafka is up.

{"level":"ERROR","timestamp":"2022-02-22T17:18:18.073Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 10.235.247.97:9092","broker":"ILRNARADEMO01:9092","clientId":"MyApp","stack":"Error: connect ECONNREFUSED 10.235.247.97:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)"}
{"level":"ERROR","timestamp":"2022-02-22T17:18:18.075Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 10.235.247.97:9092","retryCount":5,"retryTime":5784}
22 Feb 19:18:18 - [red] Uncaught Exception:
22 Feb 19:18:18 - [error] KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 10.235.247.97:9092
    at Socket.onError (C:\ProgramData\Node-red\node_modules\kafkajs\src\network\connection.js:152:23)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
C:\Windows\system32>

Is there a way around this (or am I doing something wrong)?

Thanks,
Omri

**Comment by bisand** [comment]
I am also experiencing this. I can try to fix and submit a pull request and cross our fingers.

```
 {"level":"ERROR","timestamp":"2024-12-19T22:30:12.517Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 85.164.190.150:19092","broker":"kafka.publicnode.eu:19092","clientId":"tibber-node-red","stack":"Error: connect ECONNREFUSED 85.164.190.150:19092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)"}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:12.517Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 85.164.190.150:19092","retryCount":3,"retryTime":1954}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:12.759Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 85.164.190.150:19092","broker":"kafka.publicnode.eu:19092","clientId":"tibber-node-red","stack":"Error: connect ECONNREFUSED 85.164.190.150:19092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)"}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:12.759Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 85.164.190.150:19092","retryCount":3,"retryTime":1930}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:12.795Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 85.164.190.150:19092","broker":"kafka.publicnode.eu:19092","clientId":"tibber-node-red","stack":"Error: connect ECONNREFUSED 85.164.190.150:19092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)"}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:12.795Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 85.164.190.150:19092","retryCount":3,"retryTime":2308}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:14.477Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 85.164.190.150:29092","broker":"kafka.publicnode.eu:29092","clientId":"tibber-node-red","stack":"Error: connect ECONNREFUSED 85.164.190.150:29092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)"}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:14.477Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 85.164.190.150:29092","retryCount":4,"retryTime":3604}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:14.694Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 85.164.190.150:29092","broker":"kafka.publicnode.eu:29092","clientId":"tibber-node-red","stack":"Error: connect ECONNREFUSED 85.164.190.150:29092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)"}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:14.694Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 85.164.190.150:29092","retryCount":4,"retryTime":3242}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:15.108Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 85.164.190.150:29092","broker":"kafka.publicnode.eu:29092","clientId":"tibber-node-red","stack":"Error: connect ECONNREFUSED 85.164.190.150:29092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)"}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:15.109Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 85.164.190.150:29092","retryCount":4,"retryTime":4578}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:17.942Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 85.164.190.150:39092","broker":"kafka.publicnode.eu:39092","clientId":"tibber-node-red","stack":"Error: connect ECONNREFUSED 85.164.190.150:39092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)"}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:17.942Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 85.164.190.150:39092","retryCount":5,"retryTime":5836}
 19 Dec 22:30:17 - [error] [kafkajs-consumer:d8292dc9c3bb3ff6] Kafka Consumer Error
 {"level":"ERROR","timestamp":"2024-12-19T22:30:18.086Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 85.164.190.150:39092","broker":"kafka.publicnode.eu:39092","clientId":"tibber-node-red","stack":"Error: connect ECONNREFUSED 85.164.190.150:39092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)"}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:18.087Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 85.164.190.150:39092","retryCount":5,"retryTime":8094}
 19 Dec 22:30:18 - [error] [kafkajs-consumer:3f23d34fc8f13832] Kafka Consumer Error
 {"level":"ERROR","timestamp":"2024-12-19T22:30:19.692Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 85.164.190.150:39092","broker":"kafka.publicnode.eu:39092","clientId":"tibber-node-red","stack":"Error: connect ECONNREFUSED 85.164.190.150:39092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)"}
 {"level":"ERROR","timestamp":"2024-12-19T22:30:19.693Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 85.164.190.150:39092","retryCount":5,"retryTime":8774}
 19 Dec 22:30:19 - [red] Uncaught Exception:
 19 Dec 22:30:19 - [error] KafkaJSNonRetriableError
   Caused by: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 85.164.190.150:39092
     at TLSSocket.onError (/data/node_modules/kafkajs/src/network/connection.js:149:23)
     at TLSSocket.emit (node:events:518:28)
     at emitErrorNT (node:internal/streams/destroy:169:8)
     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by omrid01** [comment]
I'm not sure the author is still maintaining this node and will pull the PR.
One solution is to set timeout parameters to expire after 10 years or so. 
In parallel, I took the code and changed it in a local branch, catching the exception (and also adding the msg object to the error message), and it works well.
But now there is a new (supported) Kafka node (`@asinino/node-red-kafkajs`) which seems to work well, so I just switched to it
